
package trailers_design;
import java.sql.*;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
/***
 * @author Frank
 */
public class ProyectoFinal extends javax.swing.JFrame {

    public ProyectoFinal() {
        initComponents();
        ConsDatos("");
        LlenaCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuActulizar = new javax.swing.JMenuItem();
        jMenuEliminar = new javax.swing.JMenuItem();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrailers = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbCveChofer = new javax.swing.JComboBox<>();
        btnGrabar = new javax.swing.JButton();
        txtKg = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        txtServCol = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        txtIdPed = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnRegresoMenu = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTpPed = new javax.swing.JTextField();
        txtTpPago = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNoCliente = new javax.swing.JTextField();
        txtIdDirec = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPagoT = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnCalc = new javax.swing.JButton();

        jMenuActulizar.setText("Actulizar");
        jMenuActulizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActulizarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuActulizar);

        jMenuEliminar.setText("Eliminar");
        jMenuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 204));
        jLabel1.setText("Datos del Servicio");

        jLabel2.setText("ID pedido");
        jLabel2.setToolTipText("");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Servicio Colonia");

        tblTrailers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTrailers.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tblTrailers);

        jLabel4.setText("Kg de carga");

        jLabel5.setText("Clave Chofer");

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnRegresoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trailers_design/regreso.png"))); // NOI18N
        btnRegresoMenu.setText("Regresar a Menu");
        btnRegresoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresoMenuActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trailers_design/escoba.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trailers_design/fondo a.png"))); // NOI18N

        jLabel8.setText("Tipo de Pedido");

        jLabel9.setText("Tipo de pago");

        jLabel10.setText("No. de Cliente");

        jLabel11.setText("ID Direccion");

        jLabel12.setText("Total");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trailers_design/trailer.jpg"))); // NOI18N

        btnCalc.setText("Calcular total");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbCveChofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPagoT)
                                    .addComponent(txtIdDirec, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNoCliente)
                                    .addComponent(txtTpPago)
                                    .addComponent(txtServCol, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdPed)
                                    .addComponent(txtKg)
                                    .addComponent(txtTpPed))
                                .addGap(139, 139, 139)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnGrabar)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(106, 106, 106)
                                                .addComponent(btnEliminar)))
                                        .addGap(36, 36, 36)
                                        .addComponent(btnActualizar)
                                        .addGap(44, 44, 44)
                                        .addComponent(btnConsultar)
                                        .addGap(43, 43, 43)
                                        .addComponent(btnBuscar)
                                        .addGap(44, 44, 44)
                                        .addComponent(btnCalc)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresoMenu)
                .addGap(55, 55, 55)
                .addComponent(btnLimpiar)
                .addGap(48, 48, 48))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addContainerGap(668, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(txtIdPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtServCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTpPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTpPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(txtPagoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCveChofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdDirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(71, 71, 71)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar)
                    .addComponent(btnEliminar)
                    .addComponent(btnActualizar)
                    .addComponent(btnConsultar)
                    .addComponent(btnBuscar)
                    .addComponent(btnCalc))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegresoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(54, 54, 54)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel3)
                    .addContainerGap(514, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void ConsDatos(String valor){
        DefaultTableModel modelo= new DefaultTableModel();
       modelo.addColumn("ID");
        modelo.addColumn("Colonia");
        modelo.addColumn("kg");
        modelo.addColumn("Tipo pedido");
        modelo.addColumn("Tipo Pago");
        modelo.addColumn("Total");
        modelo.addColumn("clave");
        modelo.addColumn("No. Cliente");
        modelo.addColumn("direccion");
        tblTrailers.setModel(modelo);
        String sql;
        ResultSet rs;
        Statement st;
        String[] datos = new String [9];
        if(valor.equals(""))
            sql="SELECT * FROM trailersd.servicio;";
        else
            sql="SELECT * FROM trailersd.servicio WHERE id_pedido = "+ valor+";";
        try{
            st=cn.createStatement();
            rs =st.executeQuery(sql);
         while(rs.next()){
             datos[0] = Integer.toString(rs.getInt(1));//pedido
             datos[1] = rs.getString(2);//sercol
             datos[2] = Integer.toString(rs.getInt(3));//kg
             datos[3] = rs.getString(4);//tipo_ped
             datos[4] = rs.getString(5);//tipo-pago
             datos[5] = Double.toString(rs.getDouble(6));//total
             datos[6] =Integer.toString(rs.getInt(7));//clave chofer
             datos[7] =Integer.toString(rs.getInt(8));//No. cliente
             datos[8] =Integer.toString(rs.getInt(9));//direccion
             modelo.addRow(datos);
            if(valor!=("")){
                txtIdPed.setText(datos[0].toString());
                txtServCol.setText(datos[1].toString());
                txtKg.setText(datos[2].toString());
                txtTpPed.setText(datos[3].toString());
                txtTpPago.setText(datos[4].toString());
                txtPagoT.setText(datos[5].toString());
                cmbCveChofer.setSelectedItem(datos[6].toString()); 
                txtNoCliente.setText(datos[7].toString());;
                txtIdDirec.setText(datos[8].toString());
              }
            } 
         tblTrailers.setModel(modelo);
         rs.close();
        }catch(SQLException ex){
            Logger.getLogger(ProyectoFinal.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    
    private void LlenaCombo(){
        String sql= "SELECT * FROM trailersd.chofer;";
        ResultSet rs;
        Statement st;
        try{
        st=cn.createStatement();
        rs = st.executeQuery(sql);
        while(rs.next()){
            String ClaveChofer=Integer.toString(rs.getInt(1));
            cmbCveChofer.addItem(ClaveChofer);
        } 
         rs.close();    
        }catch (SQLException ex){
            Logger.getLogger(ProyectoFinal.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    public void  limpiarDatos(){
        txtIdPed.setText("");
        txtServCol.setText("");
        txtKg.setText("");
        txtTpPed.setText("");
        txtTpPago.setText("");
        txtPagoT.setText("");
        txtNoCliente.setText("");
        txtIdDirec.setText("");
        cmbCveChofer.setSelectedIndex(-1);
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String codigo=txtIdPed.getText();
        limpiarDatos();
        ConsDatos(codigo);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        try{
            PreparedStatement pst =cn.prepareStatement("INSERT INTO trailersd.servicio"
         // + "(id_pedido, serviciocol, kg_carga, tipo_pedido, tipo_pago, total, chofer_clave, no_cliente, id_direccion	)"
         + " VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?);");
            int ic =(Integer.parseInt( txtIdPed.getText()));
            pst.setInt(1, ic);
            
            pst.setString(2, txtServCol.getText());
            
            int dc = Integer.parseInt(txtKg.getText());
            pst.setInt(3, dc);
            
            pst.setString(4, txtTpPed.getText());
            
            pst.setString(5, txtTpPago.getText());//txtPagoT
            
            Double kc = Double.parseDouble(txtPagoT.getText());
            pst.setDouble(6, kc);
            
            System.out.println(cmbCveChofer.getSelectedItem());
            int ii = (Integer.parseInt(cmbCveChofer.getSelectedItem().toString()));
            pst.setInt(7, ii);
            
            int wc = Integer.parseInt(txtNoCliente.getText());
            pst.setDouble(8, wc);
            
            int ec = Integer.parseInt(txtIdDirec.getText());
            pst.setDouble(9, ec);
            
            System.out.println("ic="+ic+" dc="+dc+" kc="+kc+" ii="+ii+" wc="+wc+" ec="+ec);
            System.out.println (pst);
            
            pst.executeUpdate();
            ConsDatos("");
        }catch (SQLException ex){
            Logger.getLogger(ProyectoFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try{
            PreparedStatement pst =cn.prepareStatement("UPDATE trailersd.servicio"
/*/id_pedido, serviciocol, kg_carga, tipo_pedido, tipo_pago, total, chofer_clave, no_cliente,
id_direccion   txtNoCliente   txtIdDirec/*/	

                + " set id_pedido = "+txtIdPed.getText()
                +", serviciocol = '"+ txtServCol.getText()+"'"
                +", kg_carga = "+ txtKg.getText()
                +", tipo_pedido = '"+ txtTpPed.getText()+"'"
                +", tipo_pago = '"+ txtTpPago.getText()+"'"
                +", total = "+ txtPagoT.getText()
                +", chofer_clave = "+cmbCveChofer.getSelectedItem().toString()
                +", no_cliente = '"+ txtNoCliente.getText()+"'"
                +", id_direccion = '"+ txtIdDirec.getText()+"'"
                +" WHERE id_pedido  = " +txtIdPed.getText()
                + ";");
            
            System.out.println(pst);
            pst.executeUpdate();
            ConsDatos("");
            limpiarDatos();
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Datos incorrectos...");
            Logger.getLogger(ProyectoFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String codigo = txtIdPed.getText();
        try{
            PreparedStatement pst = cn.prepareStatement("DELETE FROM trailersd.servicio WHERE id_pedido = "
                + codigo + ";");
            int valor = JOptionPane.showConfirmDialog(null, "¿Estás seguro de Borrar el registro?",
                "Confirma Elminación", JOptionPane.YES_NO_OPTION);
            System.out.println(pst);
            if(valor == 0){
                pst.executeUpdate();
                limpiarDatos();
                ConsDatos("");
            }
        }catch (SQLException ex){
            Logger.getLogger(ProyectoFinal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Datos incorrectos...");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        limpiarDatos();
        ConsDatos("");
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnRegresoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresoMenuActionPerformed
        this.setVisible(false);
        InicioTrailerDes f=  new InicioTrailerDes();
        f.setVisible(true);
    }//GEN-LAST:event_btnRegresoMenuActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarDatos();
        DefaultTableModel modelo= new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Colonia");
        modelo.addColumn("kg");
        modelo.addColumn("Tipo pedido");
        modelo.addColumn("Tipo Pago");
        modelo.addColumn("Total");
        modelo.addColumn("clave");
        modelo.addColumn("No. Cliente");
        modelo.addColumn("direccion");

        tblTrailers.setModel(modelo);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jMenuActulizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActulizarActionPerformed
         int fila=tblTrailers.getSelectedRow();
        if(fila>=0){
            txtIdPed.setText(tblTrailers.getValueAt(fila,0).toString());
            txtServCol.setText(tblTrailers.getValueAt(fila,1).toString());
            txtKg.setText(tblTrailers.getValueAt(fila,2).toString());
            txtTpPed.setText(tblTrailers.getValueAt(fila,3).toString());
            txtTpPago.setText(tblTrailers.getValueAt(fila,4).toString());
            txtPagoT.setText(tblTrailers.getValueAt(fila,5).toString());
            cmbCveChofer.setSelectedItem(tblTrailers.getValueAt(fila,6).toString());
            txtNoCliente.setText(tblTrailers.getValueAt(fila,7).toString());
            txtIdDirec.setText(tblTrailers.getValueAt(fila,8).toString());
        }
        else{
            JOptionPane.showMessageDialog(null, "No selecciono  ninguna fila");
        }  
    }//GEN-LAST:event_jMenuActulizarActionPerformed

    private void jMenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarActionPerformed
        // TODO add your handling code here:
        String codigo;
        int fila=tblTrailers.getSelectedRow();
        if(fila>=0){
            codigo=tblTrailers.getValueAt(fila,0).toString();
            try{
             PreparedStatement pst =cn.prepareStatement("DELETE FROM trailersd.servicio WHERE id_pedido ="
                     +codigo+";");
                
            int valor = JOptionPane.showConfirmDialog(null,"¿Estas Seguro de borrar el registro?"
                    ,"Confrimar Eliminacion",JOptionPane.YES_NO_OPTION);
            if(valor==0){
            pst.executeUpdate();
            ConsDatos("");
            }
            }catch (SQLException ex){
            
            Logger.getLogger(ProyectoFinal.class.getName()).log(Level.SEVERE, null,    ex);
          } 
        }
        else{
            JOptionPane.showMessageDialog(null, "No selecciono  ninguna fila");
        }
        limpiarDatos();
    }//GEN-LAST:event_jMenuEliminarActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        CalcTD c=  new CalcTD();
      c.setVisible(true);
    }//GEN-LAST:event_btnCalcActionPerformed
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try{
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFe el");
            //UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
            //UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
            //UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel";
            //UIManager.setLookAndFeel("com.jtattoo.plaf.luna.LunaLookAndFeel");
            //UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
            //UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
            //UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");
            //UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
             UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
            //UIManager.setLookAndFeel("com.jtattoo.plaf.fast.FastLookAndFeel");
            //UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            //UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
            }
            catch (Exception e) {JOptionPane.showMessageDialog(null, e);
            }
        //</editor-fold>    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoFinal().setVisible(true);
            }
        });
    }
   ConexionTD cc = new ConexionTD();
    Connection cn = cc.conexion();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresoMenu;
    private javax.swing.JComboBox<String> cmbCveChofer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuActulizar;
    private javax.swing.JMenuItem jMenuEliminar;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTrailers;
    private javax.swing.JTextField txtIdDirec;
    private javax.swing.JTextField txtIdPed;
    private javax.swing.JTextField txtKg;
    private javax.swing.JTextField txtNoCliente;
    private javax.swing.JTextField txtPagoT;
    private javax.swing.JTextField txtServCol;
    private javax.swing.JTextField txtTpPago;
    private javax.swing.JTextField txtTpPed;
    // End of variables declaration//GEN-END:variables
}
